### ISSUE TITLE
Cannot get out of  M-o menu at once

### ISSUE THREAD

**Issue by tttuuu888** [tumashu/ivy-posframe#103]
Hello @tumashu.  I just found this issue.
I cannot got out of `M-o` menus at once by `ESC` or `C-g`. I need to press `ESC` or `C-g` twice to escape from `M-o` menu. 

The below screenshot explains all. 

![esc](https://user-images.githubusercontent.com/8042298/101934354-d11eaa80-3c20-11eb-8c82-9903e9fafc38.png)

You may reproduce with below steps.
` $ emacs -Q`
```
(package-initialize)
(require 'ivy)
(require 'ivy-posframe)
(ivy-posframe-mode 1)
```
`M-x ivy-switch-buffer`
`M-o`
`ESC` or `C-g`
then you can see "^[ is not bound" on minibuffer. ("^G is not bound", in case of `C-g`)

Thanks.

**Comment by tttuuu888** [comment]
Ah I was a bit confused. `ESC` or `C-g` escapes from `M-o` menus.
It just additionally enlarges minibuffer and print "^[ is not bound" as in the screenshot.
Thanks.

**Comment by tttuuu888** [comment]
I found one more symptom related to this issue.
Pressing `M-o` from `M-o` menu supposed to escape right away too.
However currently it print message "Wrong type argument: characterp, 134217839" and go back to normal menu after about 2 seconds.
Though Pressing `ESC` from `M-o` menu escape right away with enlarging minibuffer with extra message.

**Comment by tttuuu888** [comment]
When it comes to `M-o` I mentioned above, there is already an open issue in ivy repository. https://github.com/abo-abo/swiper/issues/2701

**Comment by tttuuu888** [comment]
To sum up this issue,

1. pressing `ESC` or `C-g` to close action list
 -> ivy-posframe shows '^[ is not bound' and minibuffer enlarged.

2. pressing `M-o` to close action list
 -> wrong type 'Wrong type argument: characterp' error occurs.
    -> ivy has same issue and I think ivy need to fix this first.

Thanks.

**Comment by tumashu** [comment]
ok
