### ISSUE TITLE
Ivy-posframe not working after exwm related update

### ISSUE THREAD

**Issue by tttuuu888** [tumashu/ivy-posframe#109]
Hello @tumashu. I just updated ivy-posframe package and I found ivy-posframe is not working at all with below message.

Error in post-command-hook (ivy--queue-exhibit): (void-variable exwm--connection)

Thank you.

**Comment by seagle0128** [comment]
Same issue here.
The condition should be `(bound-and-true-p exwm--connection)`?

**Comment by tumashu** [comment]
should be fixed.

**Comment by tttuuu888** [comment]
@tumashu  I see the issue is solved since your last commit. I'm closing the issue. Thank you.
