### ISSUE TITLE
ivy-posframe-display-at-frame-bottom-center - not implemented

### ISSUE THREAD

**Issue by mihaiolteanu** [tumashu/ivy-posframe#118]
`ivy-posframe-display-at-frame-bottom-center` is not implemented, though the functionality is there.

I've had success with defining and using it like,
```
(defun ivy-posframe-display-at-frame-bottom-center (str)
      "Display the posframe at bottom center."
      (ivy-posframe--display str #'posframe-poshandler-frame-bottom-center))
```

Maybe there is a reason for the missing code or maybe it's just a glitch.

**Comment by tumashu** [comment]
Fixed.
