### ISSUE TITLE
Suppress minibuffer output

### ISSUE THREAD

**Issue by PythonNut** [tumashu/ivy-posframe#12]
I find I am often distracted by the movement left by my typing in the minibuffer. Is there a way we can just make the minibuffer blank while `ivy-posframe` is being used?

**Comment by tumashu** [comment]
At the moment, no

**Comment by JJPandari** [comment]
@tumashu And besides trying to hide minibuffer, can we make all non-ivy minibuffer inputting operations happen in a posframe? So I can always look at the posframe to type in when asked for input.

**Comment by tumashu** [comment]
ivy-posframe just show minibuffer's content and can not be focused, if you disable minibuffer, how to input?

**Comment by JJPandari** [comment]
Ah I see, so I'm not inputting in the posframe, but rather, the posframe syncs minibuffers content.哦其实不是在posframe里input只是把minibuffer的内容同步到posframe里啊。  

Disable/hide minibuffer(original point of this issue) is not bad but my point is not related to it. I mean, there are other operations like `M-:` that has no posframe shown, but it would be good if I have a posframe at point when I use `M-:`, so can we make this happen? 我是说，把minibuffer藏起来是不错，但是我说的跟它是不相关的问题。`M-:`之类的操作现在还是要去看minibuffer的，我希望我能在一个类似ivy-posframe的at point的地方来输入，这样所有minibuffer的输入都可以在point附近完成了，不会发生有时候还是要去看minibuffer的问题。  

Maybe I should open another issue...

**Comment by yanghaoxie** [comment]
@tumashu 

1. Could you please give us a snippet to make minibuffer foreground=backgound when ivy-posframe is displaying.
2. I found a snippet from helm, but I cannot adopt it to `ivy-posframe` due to lack skill of `elisp`.
```
(defun spacemacs//helm-hide-minibuffer-maybe ()
  "Hide minibuffer in Helm session if we use the header line as input field."
  (when (with-helm-buffer helm-echo-input-in-header-line)
    (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
      (overlay-put ov 'window (selected-window))
      (overlay-put ov 'face
                   (let ((bg-color (face-background 'default nil)))
                     `(:background ,bg-color :foreground ,bg-color)))
      (setq-local cursor-type nil))))
(add-hook 'helm-minibuffer-set-up-hook
          'spacemacs//helm-hide-minibuffer-maybe)
```

**Comment by tumashu** [comment]
(setq ivy-posframe-hide-minibuffer t)

**Comment by yanghaoxie** [comment]
Thank you so much!
