### ISSUE TITLE
ivy minibuffer doesn't display Korean characters

### ISSUE THREAD

**Issue by daehwannam** [tumashu/ivy-posframe#120]
When I type Korean characters in ivy minibuffer, the buffer doesn't display the characters until a non-Korean character is inserted or `toggle-input-method` is called.

For example, 
- My config includes `(setq default-input-method 'korean-hangul)`.
- I call `swiper` and `toggle-input-method` by C-\\ then type "한국" in the minibuffer, but it doesn't display the word:
![ivy-posframe-typing1](https://user-images.githubusercontent.com/35688291/149718182-31993806-d11a-410a-83ed-e9fc5fcb46b1.png)
- Once I insert a space character (or `call toggle-input-method` by C-\\) then the word is displayed:
![ivy-posframe-typing2](https://user-images.githubusercontent.com/35688291/149718206-59a36c78-2ab2-4365-b00a-0cfde4e9df7b.png)

This problem also occurs in other ivy/counsel functions such as `ivy-switch-buffer` or `counsel-find-file`.
In contrast, typing Korean characters is well displayed with the default ivy minibuffer by `ivy-display-function-fallback`.

Thanks.

**Comment by tumashu** [comment]
ivy-posframe do not support input method of emacs.

在 2022-01-17 14:35:16，"Daehwan Nam" ***@***.***> 写道：


When I type Korean characters in ivy minibuffer, the buffer doesn't display the characters until a non-Korean character is inserted or toggle-input-method is called.

For example,

My config includes (setq default-input-method 'korean-hangul).
I call swiper and toggle-input-method by C-\ then type "한국" in the minibuffer, but it doesn't display the word:

Once I insert a space character (or call toggle-input-method by C-\) then the word is displayed:


This problem also occurs in other ivy/counsel functions such as ivy-switch-buffer or counsel-find-file.
In contrast, typing Korean characters is well displayed with the default ivy minibuffer by ivy-display-function-fallback.

Thanks.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daehwannam** [comment]
I'm sorry to hear that. I hope to find a solution in the future.

**Comment by tumashu** [comment]
the problem is posframe use different buffer to show candidate, while im's candidate is in minibuffer

**Comment by daehwannam** [comment]
Thanks for the tip. Now, I see what you means.
I could check that emacs's minibuffer and ivy-minibuffer are not synchronized when typing Korean characters, after evaluating the following code:
```(setq ivy-posframe-hide-minibuffer nil)```

Currently, enable minibuffer would be an alternative solution for me. Thanks.

**Comment by tumashu** [comment]
vertico-posframe use different approach, which maybe has no this problem, but i do not know this approach stable or not. need more time to observe

在 2022-01-17 17:13:17，"Daehwan Nam" ***@***.***> 写道：


Thanks for the tip. Now, I see what you means.
I could check that emacs's minibuffer and ivy-minibuffer are not synchronized when typing Korean characters, after evaluating the following code:
(setq ivy-posframe-hide-minibuffer nil)

Currently, enable minibuffer would be an alternative solution for me. Thanks.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daehwannam** [comment]
I've just tried `vertico-posframe` by following its README.org, but unfortunately it doesn't make any different with vanilla ivy.

Also, I'm thinking that ivy has an fundamental problem with Korean (or CJK) characters because emacs doesn't recognize typing the chracters as  `self-insert-command`. Therefore, ivy cannot update candidates while typing Korean characters, although ivy's default minibuffer displays the characters.

**Comment by tumashu** [comment]
vertico-posframe need vertico, not need ivy   :-)

**Comment by daehwannam** [comment]
Oh, I didn't know about vertico. I need to check whether vertico meets my needs ;)

**Comment by daehwannam** [comment]
I've recently found a solution for the issue of Ivy and the input method for Korean:
https://github.com/abo-abo/swiper/issues/3057
