### ISSUE TITLE
An additional preview frame ala nvim's telescope

### ISSUE THREAD

**Issue by asok** [tumashu/ivy-posframe#125]
Hi,
I was wondering if it's possible to have a similar functionality like nvim's [telescope](https://github.com/nvim-telescope/telescope.nvim). That is fire up 2 posframes one with the candidates list and another one with a preview (be it the function's doc in case of `counsel-M-x` or buffer contents in case of `counsel-switch-buffer`).

A screenshot showing the telescope's look:
<img width="787" alt="Screenshot 2023-05-12 at 22 22 52" src="https://github.com/tumashu/ivy-posframe/assets/120457/74cf0b78-de51-42d2-a6d9-2b5d68752c67">

**Comment by tumashu** [comment]
It is possible, but not simple job.

**Comment by asok** [comment]
Indeed I've tried to hack something in this package, but it didn't quit fit into it's philosophy. 

In the meantime I've found out that consult package has the preview feature which is very similar to telescope's one.
