### ISSUE TITLE
How to use the default display function in specific commands

### ISSUE THREAD

**Issue by akirak** [tumashu/ivy-posframe#15]
I know it is possible to override the display function of a specific command by customizing `ivy-display-functions-alist`, but how about using the default display function of Ivy only in certain commands? For example, I am using ivy-posframe as the default display function of Ivy, but I prefer using the default  (i.e. no posframe) minibuffer-style function in swiper. Adding `(swiper . nil)` doesn't seem to take effect.

**Comment by tumashu** [comment]
Temp override ivy-alist-setting, and run swiper, you will find the *proper* function, need to setting
```
(defun ivy-alist-setting (alist &optional key)
  "Return the value associated with KEY in ALIST, using `assq'.
KEY defaults to the last caller of `ivy-read'; if no entry is
found, it falls back to the key t."
  (let ((s (cdr (or (let ((caller (or key (ivy-state-caller ivy-last))))
                      (and caller (assq caller alist)))
                    (assq t alist)))))
    (princ s)
    (princ "\n")
    s
    ))
```

**Comment by tumashu** [comment]
```
but I prefer using the default (i.e. no posframe) minibuffer-style function in swiper. Adding (swiper . nil) doesn't seem to take effect.
```
I have tested the similar issue,  how do you invoke swiper, if you use global-key-bind to invoke swiper, you should set swiper's ivy-display function, if you invoke swiper with M-x
you should set M-x's ivy-display function

**Comment by akirak** [comment]
I am not using `ivy-posframe` now. Maybe I'll check it later.

**Comment by conao3** [comment]
Now, you can. see [README](https://github.com/tumashu/ivy-posframe#per-command-mode)

**Comment by akirak** [comment]
Thanks.

**Comment by conao3** [comment]
When you have any problems, feel free to reopen this issue!
