### ISSUE TITLE
Ivy Input focus deactivated when mouse enters (hovers) posframe

### ISSUE THREAD

**Issue by deadtrickster** [tumashu/ivy-posframe#16]
How to reproduce 

- Open ivy posframe somehow (I have it on C-x b)
- Move mouse pointer here
- Start typing
- Notice garbage on last option line
- Click on other option and type again
- Notice garbage here too
- Notice `ivy-next-line` and `ivy-previous-line` (C-p/n) no longer work
- Switch to other app
- switch back to Emacs
- Notice some/all typed garbage disappeared.

![screenshot_2018-12-26_17-19-18](https://user-images.githubusercontent.com/172311/50451125-69d39700-0932-11e9-94a5-ce42114e4b9f.png)

Thanks

**Comment by deadtrickster** [comment]
Oh, sometimes I get posframe buffer scrolled horizontally :fearful:. Say instead of *scratch* I will see "atch*". Thinking related to clicking too.

![screenshot_2018-12-26_17-33-51](https://user-images.githubusercontent.com/172311/50451462-70fba480-0934-11e9-860f-234410991bb9.png)

Once happend buffer `ivy-posframe-buffer` stays scrolled till manually killed by kill-buffer.

**Comment by deadtrickster** [comment]
What's even more confusing regarding mouse interaction is that I still have tooltips like

`mouse-1: Exit the minibuffer with the selected candidate'
aand
`mouse-3: Disaply alternative actions.`

when hovering over items.

**Comment by tumashu** [comment]
posframe do not support mouse, you should not click it

**Comment by tumashu** [comment]
In most window-manager, when you mouse move or click posframe, it just do nothing, but some window-manager do not better support emacs's childframe, so when you move mouse onto it, it will get focus, In current time, I just move mouse to 0,0 to handle this problem

**Comment by deadtrickster** [comment]
ok, what about scrolling issue? when search matches long strings the frame scrolled as described and essentially becomes unusable till I kill it
