### ISSUE TITLE
Use a minor mode

### ISSUE THREAD

**Issue by noctuid** [tumashu/ivy-posframe#18]
Instead of requiring a restart to toggle ivy-posframe, would it be possible to use a minor mode? Here are some things that would need to be changed:

- Use remaps (e.g. `[remap ivy-read-action]`) in an `ivy-posframe-mode-map` instead of altering `ivy-minibuffer-map` or binding specific keys
- Undo advice when disabling the minor mode

Is there anything else that I'm missing?

**Comment by tumashu** [comment]
We need to change ivy-minibuffer-map, If we can find a way to revert the change safely, ivy-posframe-minor-mode is possible, but emacs have not method to advice a variable.

**Comment by noctuid** [comment]
Since you're already advising `ivy--minibuffer-setup`, how about enabling a minor mode in `ivy-posframe--minibuffer-setup` and binding remaps in that minor mode keymap instead of `ivy-minibuffer-map`. That seems to work as expected for me. Then an `ivy-posframe-disable` could be added that would remove the advice.

**Comment by conao3** [comment]
Now `ivy-posframe` is minor-mode in #43 :tada:
