### ISSUE TITLE
Should the default width be the frame instead of the window?

### ISSUE THREAD

**Issue by seanfarley** [tumashu/ivy-posframe#22]
Currently, the width is calculated by:

```lisp
(or ivy-posframe-width (/ (window-width) 2))
```

but should this be using the frame width instead?

```lisp
(or ivy-posframe-width (/ (frame-width) 2))
```

Since the childframe spans windows anyways, it seems to me that the frame width should be used, no?

**Comment by tumashu** [comment]
Fixed, thanks!

**Comment by seanfarley** [comment]
Thanks!
