### ISSUE TITLE
Setting `mouse-autoselect-window` to `t` causes minibuffer to lose focus when there is more than one window

### ISSUE THREAD

**Issue by leungbk** [tumashu/ivy-posframe#23]
Recipe:

- `(setq mouse-autoselect-window t)`
-  `(split-windows-horizontally)`
- Move mouse to the right window and `M-x` a function that uses `ivy-posframe-display-at-point`, without moving the mouse again

Since the mouse zips back to the upper-left corner of the frame, the left window is selected because of this custom setting, and keystrokes are fed to the left window instead of the minibuffer. 

From poring over some mouse-position functions with `C-h f`, I notice several functions that deal with the mouse's position in a frame, but none dealing with the mouse's position in a window.

**Comment by tumashu** [comment]
Try:
```
(setq posframe-mouse-banish nil)

```

**Comment by leungbk** [comment]
Thanks!
