### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by kinnala** [tumashu/ivy-posframe#25]
It's hard to explain what's going on without screenshots.

counsel-M-x looks like this:
![Screenshot from 2019-03-09 17-28-01](https://user-images.githubusercontent.com/973268/54073565-73ae3a80-4291-11e9-92e7-141ed7f3e4dc.png)

swiper looks like this:
![Screenshot from 2019-03-09 17-28-06](https://user-images.githubusercontent.com/973268/54073568-7f016600-4291-11e9-9ea2-6736a1bdd856.png)

I have the latest version from master with the following configuration:
```elisp
(use-package ivy-posframe
  :after counsel
  :init
  (progn
    (push '(counsel-M-x . ivy-posframe-display-at-frame-center) ivy-display-functions-alist)
    (push '(ivy-switch-buffer . ivy-posframe-display-at-frame-center) ivy-display-functions-alist)
    (ivy-posframe-enable)
    (set-face-attribute 'internal-border nil :background "gray50")
    (setq ivy-posframe-border-width 1)))
```

Emacs version is the following
```
GNU Emacs 26.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.23.2) of 2018-08-13
```

Disabling `ivy-rich` didn't fix it.

This is my ivy configuration:
```elisp
(use-package ivy
  :init
  (progn
    (ivy-mode 1)
    (setq ivy-height 13
	  ivy-fixed-height-minibuffer t
       	  ivy-use-virtual-buffers t
          enable-recursive-minibuffers t))
  :bind (("C-x b" . ivy-switch-buffer)
         ("C-c r" . ivy-resume)
	 ("C-x C-b" . ivy-switch-buffer)))

(use-package counsel
  :after python
  :bind (("M-x" . counsel-M-x)
	 ("C-x C-f" . counsel-find-file)
	 ("C-c g" . counsel-ag)
         ("C-c G" . counsel-git)
         ("M-y" . counsel-yank-pop))
  :bind (:map python-mode-map
              ("C-c C-j" . counsel-imenu))
  :init (setq counsel-find-file-ignore-regexp "\\archive\\'"))

(use-package swiper
  :bind ("C-c s" . swiper))

(use-package ivy-hydra)
```

Thanks for any tips.

**Comment by kinnala** [comment]
The first screenshot was fixed by removing
```elisp
(setq ivy-fixed-height-minibuffer t)
```
The latter remains (= swiper is empty).

**Comment by tumashu** [comment]
I have try to fix the problem, please test again, if does not work remain, please
set: (setq ivy-posframe-hide-minibuffer nil)

**Comment by conao3** [comment]
This issue also looks like an issue related to `ivy-fixed-height-minibuffer`.
The problem (#34) associated with the variable has been solved, is it still an issue?

**Comment by conao3** [comment]
Close. Feel free to reopen it when it still an issue.
