### ISSUE TITLE
Not compatible with window-purpose

### ISSUE THREAD

**Issue by yanghaoxie** [tumashu/ivy-posframe#26]
When all windows of a buffer are dedicated to windows (set by `purpose-toggle-window-buffer-dedicated`), if I use `ivy-switch-buffer` to switch buffer, the buffer will be opened in posframe. I give am example as follows (the posframe is in the center).
![ivy-posframe-window-purpose-bug](https://user-images.githubusercontent.com/10540480/54197444-ee2fc200-44fe-11e9-8d99-72ce30b84a23.png)

**Comment by conao3** [comment]
This issue related to window-purpose. Close for now, but feel free to reopen when any updates.
