### ISSUE TITLE
[Question] Padding/border to posframe?

### ISSUE THREAD

**Issue by jojojames** [tumashu/ivy-posframe#3]
Hey,

Curious how you'd add padding/border to the posframe. I find the frame that pops up blends end with the background so it's tricky to see where the frame is.

Thanks!

**Comment by tumashu** [comment]
adding padding/border  is a simple thing, the other method to deal with this is set ivy-posframe-face :-)

**Comment by Townk** [comment]
I trying to find how to set the visual border on the child frame and couldn't. Could you give us an example of how should I change ivy-posframe-face to have a border?

**Comment by tumashu** [comment]
```
how should I change ivy-posframe-face to have a border?
```
It can resolve the problem:  blends end with the background,  but it can not add a border.

In the new code, you can use ivy-posframe-parameters to add left-fringe and right fringe,
which may useful.

**Comment by tumashu** [comment]
You can customize ivy-format-function to add a text border :-)

```
(defun ivy-format-function-default (cands)
  "Transform CANDS into a string for minibuffer."
  (concat "--------------------------\n"
          (ivy--format-function-generic
           (lambda (str)
             (concat "|> " (ivy--add-face str 'ivy-current-match) ""))
           (lambda (str)
             (concat "|  " str ""))
           cands
           "\n")
          "\n`--------------------------\n"
          ))

```

**Comment by tumashu** [comment]
Set ivy-posframe-border-width to 10 and customize face 'internal-border'

**Comment by deadtrickster** [comment]
What to do if I want different color border and paddings at the same time?

**Comment by tumashu** [comment]
border's face is  internal-border and paddings' face is fringle

**Comment by deadtrickster** [comment]
ok but fringe can be only left or right? how about top and bottom

**Comment by tumashu** [comment]
have no good way at the moment about top and bottom
