### ISSUE TITLE
focus can go out of frame with multi line collections

### ISSUE THREAD

**Issue by CeleritasCelery** [tumashu/ivy-posframe#31]
ivy-posframe is only `ivy-height` lines tall. This means that if the candidates span multiple lines and you scroll down the selection can go out of view. Ivy handles this by scrolling in the minibuffer. We will have to add a function to make sure that selected line does not go out of frame.

**Comment by tumashu** [comment]
truncate-lines?

**Comment by tumashu** [comment]
Please try again, maybe this version is more comforatble

**Comment by CeleritasCelery** [comment]
> truncate-lines?

Surprisingly, I had not thought of that. 

> Please try again, maybe this version is more comforatble

while this certain solves the issue, I feel like it doesn't "behave well". If you are scrolling and get a line that is really long, it all the sudden makes the posframe occupy your entire display, which is a little jarring. In my testing of it, it can make the posframe jump around a lot as it tires to accommodate every line. I honestly feel like truncate lines may be a better solution.

**Comment by tumashu** [comment]
truncate-lines has another problem, it will let some info hide.

**Comment by CeleritasCelery** [comment]
that is true
