### ISSUE TITLE
Support swiper-isearch

### ISSUE THREAD

**Issue by seagle0128** [tumashu/ivy-posframe#34]
@abo-abo added a new command `swiper-isearch` which is faster, but `ivy-posframe` doesn't support it. Both the minibuffer and child frame are displayed.

![image](https://user-images.githubusercontent.com/140797/56082888-e42c1680-5e50-11e9-85a5-c38941374148.png)

**Comment by conao3** [comment]
`ivy-posframe` works normally when I comment out `(ivy-fixed-height-minibuffer t)` in `let`.

**Comment by conao3** [comment]
If the user sets `ivy-fixed-height-minibuffer` to` t` in global, the same problem appears for all ivy functions.
We have to make ivy ignore this variable when `ivy-posframe` is enabled.
![Capture 2019-04-14 11 46 38](https://user-images.githubusercontent.com/4703128/56087693-14a09e80-5eab-11e9-930c-2d5cc4353d1d.png)

**Comment by tumashu** [comment]
seq this vairable in ivy-posframe-enable?

**Comment by conao3** [comment]
It is valid if it is set globally, but it does not work if it is let-bound like this.
The value of let binding takes precedence over the value of global.

We need to set it to `nil` before the value is used in `ivy-read` or more directly `ivy--minibuffer-setup`.
There are various ways to accomplish this, either using advice or using hooks, depending on the developer's preferences.

**Comment by conao3** [comment]
oops, sorry. My English is bad.
We have to make ivy ignore this variable `when` ivy-posframe is enabled.
=> We have to make ivy ignore this variable `while` ivy-posframe is enabled.

(I keep in mind that this package can be enabled or disabled as a minor mode in the future.)

**Comment by tumashu** [comment]
I prefer advice-add to setq variable,  for we have advice-add ivy--minibuffer-setup now,

**Comment by tumashu** [comment]
```
(defun ivy-posframe--minibuffer-setup (orig-func)
  "Advice function of `ivy--minibuffer-setup'."
  (funcall orig-func)
  (when (and ivy-posframe-hide-minibuffer
             ;; only hide minibuffer's info when posframe is showed.
             ivy-posframe--display-p)
    (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
      (overlay-put ov 'window (selected-window))
      (overlay-put ov 'face
                   (let ((bg-color (face-background 'default nil)))
                     `(:background ,bg-color :foreground ,bg-color)))
      (setq-local cursor-type nil))))

```

**Comment by conao3** [comment]
I did not find advice on `ivy--minibuffer-setup`.
It seems better to `let` this variable be `nil` with let and call the original function.

**Comment by tumashu** [comment]
ivy-posframe.el 409 line
