### ISSUE TITLE
ivy-posframe-font seems take no effect.

### ISSUE THREAD

**Issue by Yanhao** [tumashu/ivy-posframe#36]
What I intend to do is setting the font of posframe to some Sans type. But seems that the ivy-posframe-font take no effect.

Below is from my init.el:
![image](https://user-images.githubusercontent.com/10085564/56468101-198cc180-645a-11e9-8ac0-100c741e7b63.png)

Is there some thing wrong in my configurations ?

**Comment by tumashu** [comment]
Should work, please try again.

**Comment by conao3** [comment]
It works for me for your information.
The former setting on `ivy-display-function` seems to be unnecessary. Because it is overwritten immediately after.

**Comment by Yanhao** [comment]
awesome, It works now.

**Comment by Yanhao** [comment]
> The former setting on `ivy-display-function` seems to be unnecessary. Because it is overwritten immediately after.

true. thx pointing out~
