### ISSUE TITLE
ivy-posframe copies prompt text as kill

### ISSUE THREAD

**Issue by tttuuu888** [tumashu/ivy-posframe#41]
First of all, thanks a lot for this great package.

Recently I found ivy-posframe  copies prompt text into kill ring.
You can reproduce this as below.
1. `(ivy-posframe-enable)`
2. `C-x C-f`
3. `C-g`
4. `C-y`
5. And then you can see  `68   Find file: ~/ ` is inserted.

Thanks.

**Comment by conao3** [comment]
This issue solved at #42.
