### ISSUE TITLE
First line disappears with the specific condition.

### ISSUE THREAD

**Issue by tttuuu888** [tumashu/ivy-posframe#47]
This is very weird but the first line of list disappears with the specific condition.
Looks like this happens only with `ivy-posframe-display-at-frame-center`.
You can reproduce with below step:
1. ` (ivy-posframe-mode 1)`
`(setq ivy-display-function #'ivy-posframe-display-at-frame-center)`
2. `C-x b *scratch*`
3. `M-<`
4. `C-u 10 C-f`
5. `C-n`
6. `C-x d`
7. You can see the first line `./` disappeared.

Thanks.

**Comment by CeleritasCelery** [comment]
the first line disappears from where? the ivy prompt?

**Comment by tttuuu888** [comment]
@CeleritasCelery from the list, the first line right under the prompt.
In case of `C-x d`, the first line is `./` and second is `../`.

**Comment by tttuuu888** [comment]
I didn't understand the whole process but it looks like this happens due to the difference between `(kill-line 1)` and `(delete-region (point) (save-excursion (line-move 1 'noerror) (point)))`

For example, if the cursor is located at $ at the below text,
`M-x $1111`
`2222`
`3333`

You can see the different result If you eval `(kill-line 1)` and  `(delete-region (point) (save-excursion (line-move 1 'noerror) (point)))`. 

So I suspected the point, and I fixed the way of pull request #48 and the issue has gone from me.
I would appreciate the other approach or opinion too.
Thanks.
