### ISSUE TITLE
[Request] new style - bottom center

### ISSUE THREAD

**Issue by rgd** [tumashu/ivy-posframe#5]
Hi!  Just read about ivy-posframe and already installed it and am using it.  Very nice!

One request:  could you add a new style "ivy-posframe-display-at-frame-bottom-center"?  
It would be a combination of bottom-left and window-center, the 'y' position would be the same as bottom-left, and the 'x' position would be the same as window-center.   (Looking at the code briefly I think it would require a change in posframe first.)    I find my eyes drawn to the center of the windows more than the edges and using ivy-posframe-display-at-frame-bottom-left is great but I think it might be a little nicer for me if it were centered on the window (or frame).

Thanks for your work!  It is appreciated.

Regards,

Rob

**Comment by tumashu** [comment]
Added

**Comment by rgd** [comment]
Thank you very much!  That looks great!
