### ISSUE TITLE
Changing default background color will change ivy-posframe color as well.

### ISSUE THREAD

**Issue by tttuuu888** [tumashu/ivy-posframe#63]
Hello. First of all, Thanks for this great package.

You can see the issue case with below steps:
1. `(custom-set-faces '(ivy-posframe ((t (:background "Red")))))`
 -> `ivy-posframe` background color is now 'Red'. Everything is okay so far.
2. `(custom-set-faces '(default ((t (:background "Black")))))`
 -> Now background color is black and `ivy-posframe` color is also changed to black.
 -> However, `(face-attribute 'ivy-posframe :background nil t)` this still shows 'Red'
3. To make `ivy-posframe` background color 'Red' again, I need to change the color to the other color first, and change to 'Red' again.
 ex)
 `(custom-set-faces '(ivy-posframe ((t (:background "Blue")))))`
 and
 `(custom-set-faces '(ivy-posframe ((t (:background "Red")))))`

Thanks.

**Comment by tttuuu888** [comment]
I didn't test many other packages but this seems happening only in `ivy-posframe`.

**Comment by tttuuu888** [comment]
This seems more like `posframe` issue though, I will continue here what I found.

I found the background color remains if I change a little bit of `posframe--create-posframe` function in `posframe.el` file.

```
;; Create child-frame
(unless (and (frame-live-p posframe--frame)
             ;; For speed reason, posframe will reuse
             ;; existing frame at possible, but when
             ;; user change args, recreating frame
             ;; is needed.
             (equal posframe--last-args args))
             ...
```
to
``` 
(when t
    ...
```

So, creating child-frame everytime solves this issue but it make `ivy-posframe` flickering by every typing.

This is what I found. I hope this would be of help. Thanks.

**Comment by tumashu** [comment]
Maybe the simplist  way is that:  run posframe-delete-all when you change theme

**Comment by tttuuu888** [comment]
@tumashu Okay I will follow your suggestion.
I'm closing this issue.
Thanks.
