### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit)

### ISSUE THREAD

**Issue by iwai** [tumashu/ivy-posframe#67]
Error occurred. hmm, it does not occur at first, but occurs from a certain timing. however, I do not know which timing ...

Error in post-command-hook (ivy--queue-exhibit): (error "No buffer named  *ivy-posframe-buffer*")

**Comment by conao3** [comment]
Thank you for the report but we cannot do anything with your information.

Please report an issue with your environment and reproducible steps in `emacs -Q`.

**Comment by iwai** [comment]
I'm sorry, this problem seems to have caused inconsistencies caused by manipulating posframe directly.
This issue is closed because it was not reproduced in the state of normal use. I'm sorry...

**Comment by conao3** [comment]
OK. Nothing bad. Happy hacking!
