### ISSUE TITLE
prompt line duplicated when it gets longer than specific size.

### ISSUE THREAD

**Issue by tttuuu888** [tumashu/ivy-posframe#71]
The prompt line is duplicated when it gets longer than a specific length. 
Below is a simple example of this issue.

![a](https://user-images.githubusercontent.com/8042298/65435886-317ace00-de5c-11e9-8a32-cd1dfa8f3712.png)

![b](https://user-images.githubusercontent.com/8042298/65435921-3dff2680-de5c-11e9-91a9-b2cd89f8b6e0.png)

This is tested with below conditions.
- Emacs 26.3
- ivy-20190825.1023
- ivy-posframe-20190819.657
- posframe-20190805.956

emacs -q
```
(require 'ivy)
(require 'ivy-posframe)
(ivy-mode)
(ivy-posframe-mode)
```

Thanks.

**Comment by tttuuu888** [comment]
I found `ivy` prompt is separated into 2 lines when it gets longer than a specific length and this issue occurs exactly at that moment.

**Comment by tttuuu888** [comment]
@tumashu  I'm sorry but my previous pull request https://github.com/tumashu/ivy-posframe/pull/72 wasn't a fundamental solution for this issue.

It works fine with the above case.  I thought the ivy prompt would expand up to 2 lines and that's actually the case for `switch-to-buffer`. However, I found that for `find-file` or `dired`, it can be extended beyond 3 lines. In this case, the prompt gets worse like this:

![aa](https://user-images.githubusercontent.com/8042298/65584728-4a9a9080-dfbc-11e9-801a-5d93d8218cc1.png)
![bb](https://user-images.githubusercontent.com/8042298/65584739-4ec6ae00-dfbc-11e9-8e37-35895aaf5242.png)

My input is duplicated and the first line of candidates is missed.

In previous version, the prompt line is duplicated but nothing is missing as below.

![cc](https://user-images.githubusercontent.com/8042298/65585163-fd6aee80-dfbc-11e9-8bc0-87a1b1c3c9ce.png)

I'm sorry again for the previous pull request that wasn't tested enough.

**Comment by tttuuu888** [comment]
I have tested so far and it seems okay. Thank you.

**Comment by zhenwenc** [comment]
After upgrading to the latest version of `ivy-posframe`, the prompt line becomes problematic on some commands, such as `counsel-projectile-rg`. Here is the GIF:

![ivy-posframe-flicker](https://user-images.githubusercontent.com/5435340/65805575-38963900-e1da-11e9-92b0-c3b4cbe7d7b2.gif)

I have tried reverting to the reversion before this changes, the above issue goes away, so I suspect that this changes causing the problem.

@tttuuu888 @tumashu Could you please take a look. Thanks!

**Comment by tttuuu888** [comment]
@zhenwenc You are right. This is caused by my commit. I thought I had tested enough, but now I know I've only tested it within the range of my use. 
I will look into this issue again. Thank you and sorry as well.

**Comment by tttuuu888** [comment]
@zhenwenc Could you please check my pull request #74 ? I need more review. I would appreciate any opinion. Thanks.

**Comment by zhenwenc** [comment]
Hey @tttuuu888 , sorry I didn't managed to test your PR yesterday. Since the PR had been merged, I can confirm that the issue had been fixed in master branch. Thanks a lot! 👍

**Comment by tttuuu888** [comment]
@zhenwenc  Thank you for confirming it. I'm closing this issue.
