### ISSUE TITLE
Weird positioning when using splits

### ISSUE THREAD

**Issue by yankcrime** [tumashu/ivy-posframe#75]
I see the following behaviour when using ivy-posframe and split windows.  Here's what it looks like with a single buffer:

<img width="1280" alt="Screenshot 2019-10-07 at 10 17 59" src="https://user-images.githubusercontent.com/436656/66299695-f06acb00-e8eb-11e9-9871-4ef79172a48b.png">

However, when I'm working with a split layout, the position is wrong:

<img width="1280" alt="Screenshot 2019-10-07 at 10 18 12" src="https://user-images.githubusercontent.com/436656/66299729-07112200-e8ec-11e9-9424-0a55553e3ac8.png">

I would expect it to stay central within the frame, as in the first screenshot.

**Comment by tumashu** [comment]
try (setq ivy-posframe-style 'frame-center)

**Comment by yankcrime** [comment]
This worked, thanks @tumashu !
