### ISSUE TITLE
Frame keep on the screen when focuse is not on the frame

### ISSUE THREAD

**Issue by baolonglin** [tumashu/ivy-posframe#76]
Emacs version: self build 27.0.50
ivy-postframe: 20190928.554

How to reproduce:
Press M-x show the posframe
Use mouse click the frame behind the posframe
The posframe keeps there, if press mouse back to the posframe, the posframe become editable
Use mouse click the frame behind the posframe
Press M-x show the error:
> Debugger entered--Lisp error: (error "Command attempted to use minibuffer while in minib...")

**Comment by conao3** [comment]
posframe doesn't support any mouse action. move https://github.com/tumashu/posframe/issues/43
