### ISSUE TITLE
make face colors inherit from custom theme?

### ISSUE THREAD

**Issue by stardiviner** [tumashu/ivy-posframe#8]
RT. The default colours ugly. In my Emacs, I'm using light custom theme, but posframe popup with black background color by default.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/378699/38452766-615fcfe6-3a7d-11e8-904b-3e609c77f5ef.png)

**Comment by tumashu** [comment]
you should customize your own ivy face, default face is not suit all user :-)

**Comment by stardiviner** [comment]
I found source code defined default face `ivy-posframe`. I think this should can be improved.
``elisp
(defface ivy-posframe
  '((t (:inherit default :background "#333333" :foreground "#dcdccc")))
  "Face used by the ivy-posframe."
  :group 'ivy-posframe)
```

**Comment by tumashu** [comment]
PR is welcome:-)

**Comment by stardiviner** [comment]
Like this?
```elisp
(defface org-scheduled
  '((((class color) (min-colors 88) (background light)) (:foreground "DarkGreen"))
    (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen"))
    (((class color) (min-colors 8)) (:foreground "green"))
    (t (:bold t :italic t)))
  "Face for items scheduled for a certain day."
  :group 'org-faces)
```

**Comment by tumashu** [comment]
Maybe, I do not fimilar emacs's face.

**Comment by tumashu** [comment]
![o3m qfr 884fqgals jq](https://user-images.githubusercontent.com/67725/50467081-23d30d80-09dc-11e9-873f-adc10a18a593.png)

I don't think so :-)

**Comment by tumashu** [comment]
@JJPandari

**Comment by dgutov** [comment]
Please use the default faces, so that the posframe window looks close to what ivy's minibuffer looks like.

**Comment by dgutov** [comment]
```emacs
(put 'ivy-posframe 'face-alias 'default)

(setq ivy-posframe-parameters
      '((left-fringe . 10)
        (right-fringe . 10)))
```

makes it better, but a slightly different background, or a colored border, would be best.

**Comment by tumashu** [comment]
maybe:
```

(setq ivy-posframe-parameters
      `((left-fringe . ,left-fringe-width)
        (right-fringe . ,right-fringe-width)))
```

**Comment by tumashu** [comment]
Now, ivy-posframe face just inhert default,  not looks very well, but not looks bad too :-)

**Comment by dgutov** [comment]
Thanks!

**Comment by tumashu** [comment]
Add a border seem to beautiful:

```
How to show a border

    M-x customize-face internal-border
    (setq ivy-posframe-border-width 1)

```

**Comment by tumashu** [comment]
![default](https://user-images.githubusercontent.com/67725/54000060-f7c4cd00-4180-11e9-91bf-fbb766aed306.png)

**Comment by dgutov** [comment]
Thanks! With the border as well, this is working better than I expected (initially I was only going to try it out briefly).

Ideally the border would be configurable purely in this package, but I see there's some problem preventing that, from your discussion on emacs-devel.

**Comment by stardiviner** [comment]
Can `ivy-posframe` or `posframe` provide a `defcustom` variable or similar to let user customize the child-frame parameters? I seems saw it somewhere, but forgot that variable name. Might add some screenshots to demonstrate that customization will help user how it works.

**Comment by tumashu** [comment]
I have added ivy-posframe-border face, update posframe and ivy-posframe, you can use ivy-posframe-parameters to set posframe's any frame parameter.

**Comment by tumashu** [comment]
@dgutov  with the help of Eli Zaretskii and martin rudalics, I have add a internal-border-color to posframe, now ivy-posframe can customize its border's color.

**Comment by rileyrg** [comment]
why is posframe using ivy anything? which faces do I need to customise to stop my posframe being unreadable with a light theme?
