### ISSUE TITLE
Frame title changing and flickering when in use

### ISSUE THREAD

**Issue by yankcrime** [tumashu/ivy-posframe#81]
Using `ivy-posframe` causes the frame title to change and results in a distracting flickering effect.  Here's a GIF that demonstrates:

![Kapture 2019-12-18 at 11 00 52](https://user-images.githubusercontent.com/436656/71080909-ff8cb580-2185-11ea-8ada-90600f6b93f2.gif)

I'm using Emacs 26.3 on macOS (10.15.2).  The version of `ivy-posframe` is 20191103.105 installed via Melpa, and my configuration is as follows:

```
(use-package ivy-posframe
 :custom-face
 (internal-border ((t (:background "#cccccc"))))
 :after (ivy)
 :config
 (setq ivy-posframe-parameters
     '((left-fringe . 8)
       (right-fringe . 8))
     ivy-posframe-border-width 1
     ivy-posframe-hide-minibuffer t
     ivy-posframe-style 'frame-center)
 (ivy-posframe-mode 1))
```

This doesn't happen if I'm using Ivy without `ivy-posframe`.

**Comment by yankcrime** [comment]
I've traced the problem to [this commit](https://github.com/tumashu/posframe/commit/e3fd09f115da6ea5809c8e443b31da954c93ffd7) introduced recently in `posframe`.

**Comment by mpereira** [comment]
I've been seeing the same for a while now. Currently running ivy-posframe 20191103.135 on Emacs 26.3 on macOS.

**Comment by tumashu** [comment]
Fixed in posframe
