### ISSUE TITLE
Posframe max-width?

### ISSUE THREAD

**Issue by ianpan870102** [tumashu/ivy-posframe#82]
Can I set the maximum width of the ivy-posframe? When I have my emacs as full screen, I felt the drop-down menu is quite unnecessarily large.
Perhaps we can use the percentage of the frame width together with a maximum width to avoid having it become too wide (less aesthetically pleasing IMO).

**Comment by tumashu** [comment]
set  ivy-posframe-width and ivy-posframe-height

**Comment by ianpan870102** [comment]
Thanks for the prompt reply! Sadly, I've already tried those two variables but in vain. For context, here's my current ivy-posframe setting:
```emacs-lisp
(use-package ivy-posframe
  :after ivy
  :diminish
  :config
  (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-center))
        ivy-posframe-height-alist '((t . 20))
        ivy-posframe-parameters '((internal-border-width . 10)))
  (ivy-posframe-mode +1))
```
The height is succesfully changed to 20 after setting `ivy-posframe-height-alist`, but there doesn't seem to be a variable called `ivy-posframe-width-alist`.

As you suggested, I've set `ivy-posframe-width` and `ivy-posframe-height` as follows:
```emacs-lisp
(use-package ivy-posframe
  :after ivy
  :diminish
  :config
  (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-center))
        ivy-posframe-parameters '((internal-border-width . 10)))

  ;; Sadly no effect
  (setq ivy-posframe-height 50)
  (setq ivy-posframe-width 50)

  (ivy-posframe-mode +1))
```
When I `M-x describe variable` the width and height, both are correctly set to 50. There are however **no visible difference** at all.

**Comment by tumashu** [comment]
I try to fix this problem, please try again

**Comment by ianpan870102** [comment]
Hi @tumashu I just updated with your commit and the `ivy-posframe-width` now works as expected! 

However, `ivy-posframe-height` still takes no effect (I'm on macOS, Emacs 27.0.50), but since `ivy-posframe-height-alist '((t . 20))` can achieve the same thing, I'll close this issue for now.

Feel free to reopen if you want to track why `ivy-posframe-height` takes no effect. Thanks again!
