### ISSUE TITLE
Setting ivy-posframe-border takes no effect?

### ISSUE THREAD

**Issue by ianpan870102** [tumashu/ivy-posframe#83]
I'd love to draw a white border around the ivy-posframe to have it further stand out from my dark theme. I've put 
```emacs-lisp
  :custom-face
  (ivy-posframe-border ((t (:background "#ffffff"))))
```
under its use-package section, but it does not take effect. On the other hand, setting ivy-posframe-cursor works as expected.

For context, this is my complete config for ivy-posframe:
```emacs-lisp
(use-package ivy-posframe
  :after ivy
  :diminish
  :custom-face
  (ivy-posframe-border ((t (:background "#ffffff"))))
  :config
  (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-top-center))
        ivy-posframe-height-alist '((t . 20))
        ivy-posframe-parameters '((internal-border-width . 10)))
  (setq ivy-posframe-width 70)
  (ivy-posframe-mode +1))
```

When describing the face of ivy-posframe-border, it does give me \#FFFFFF
```
           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #ffffff
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: internal-border
```

**Comment by conao3** [comment]
What WM do you use?
Currently, posframe has some limitations in mac normal build (NS) and linux on GNOME.

**Comment by ianpan870102** [comment]
> ...has some limitations in mac normal build (NS) and linux on GNOME
Hmm, that must be it. I'm using macOS Catalina with Emacs 27.0.50.

Feel free to close this issue if improving WM-wise is out of the scope of this project.

**Comment by conao3** [comment]
OK, you maybe have used mac normal build (NS) Emacs.
The border issue had reported in [posframe issue tracker](https://github.com/tumashu/posframe/issues/30). Therefore, please subscribe to that issue instead of this.
