### ISSUE TITLE
conflict with persp-mode

### ISSUE THREAD

**Issue by tshu-w** [tumashu/ivy-posframe#89]
#### Reproduction guide 
actiavate `persp-mode` and use `persp-load-state-for-file` to load last state.
#### `ivy-posframe` config
```emacs-lisp
(use-package ivy-posframe
  :hook (ivy-mode . ivy-posframe-mode)
  :init
  (setq ivy-posframe-parameters '((left-fringe . 8) (right-fringe . 8))
        ivy-posframe-width 120
        ivy-posframe-display-functions-alist '((swiper . nil)
                                               (complete-symbol . ivy-posframe-display-at-point)
                                               (t . ivy-posframe-display-at-frame-center))))
```
#### System Info :computer:
- OS: darwin
- Emacs: 26.3
<img width="1380" alt="Screen Shot 2020-03-04 at 8 48 18 AM" src="https://user-images.githubusercontent.com/13161779/75836798-f6fb6100-5dfd-11ea-84f6-eb85feb878f9.png">

**Comment by tumashu** [comment]
try (setq posframe-mouse-banish t)

**Comment by tshu-w** [comment]
This doesn't help. I delete `ivy-posframe-buffer` after run `persp-load-state-for-file` as an workaround. Leave this issue open temporarily.

**Comment by weitongdao** [comment]
呆神，请问下，pyim五笔候选框在 ivy-posframe中无法显示，只能通过盲猜输入汉字候选词条。 @tumashu

**Comment by tshu-w** [comment]
@tumashu I think it's persp-mode and I don't use it now, so I close this issue. @weitongdao you can open another issue.
