### ISSUE TITLE
Display point 

### ISSUE THREAD

**Issue by julienfantin** [tumashu/ivy-posframe#9]
Are there any issues preventing from displaying the point inside the child-frame?

**Comment by tumashu** [comment]
sorry, i can not understand your mean, do you want to not show cursor in child-frame?

**Comment by julienfantin** [comment]
The issue is I cannot see the point in ivy's posframe.

Here's a screenshot:

![screen shot 2018-05-22 at 8 43 48 pm](https://user-images.githubusercontent.com/127283/40397478-05c2ab8e-5e01-11e8-93a3-1d637ab93acf.png)

I would expect to see the box cursor after `ivy-pos`, but from the look of your screenshots this is just how the library currently works?

I wish the cursor was visible because it makes it difficult to do even trivial edits without looking down at the minibuffer.

**Comment by tumashu** [comment]
Updated, try again.
