### ISSUE TITLE
Sometimes ivy-posframe will disappear under some edge cases

### ISSUE THREAD

**Issue by stardiviner** [tumashu/ivy-posframe#91]
Sometimes when I pressed `[C-g]` or other keybindings caused ivy-posframe hidden, When I select windows with number with `ace-window`, it shows a window number for the hidden ivy-posframe. At that time I can see error message in minibuffer.
```
Error in post-command-hook (ivy--queue-exhibit): (error "Selecting deleted buffer")
```
Is there a way to fix this?
I mean in ivy-posframe source code. (I can manually select this hidden frame window, and close it manually, but it's anonying).

**Comment by tumashu** [comment]
please first try (setq posframe-mouse-banish t)

**Comment by stardiviner** [comment]
Ok, I added it to my init config, I error happens again. I will re-open issue. For now, I close it now. Thanks @tumashu
