### ISSUE TITLE
Integration with swiper-isearch-toggle

### ISSUE THREAD

**Issue by hnnazm** [tumashu/ivy-posframe#93]
I used Isearch mainly for searching and navigating and sometime use swiper for doing bigger search. So I bound  a key to `swiper-isearch-toggle` . The problem is when I do my Isearch and swiper I just want to used the default minibuf to avoid blocking my view.
When I toggle from Isearch to swiper, the frame is are not obeying the swiper function.

I tried this function but didn't work.
`(setq ivy-posframe-display-functions-alist`
`'((swiper          . nil)`
`(t               . ivy-posframe-display-at-frame-center)))`
`(ivy-posframe-mode 1)`

I also try this
`(setq ivy-posframe-display-functions-alist`
`    '((swiper-isearch-toggle          . nil)`
`    (t               . ivy-posframe-display-at-frame-center)))`
`(ivy-posframe-mode 1)`
and still didn't work.

Any idea how could I achieve this?

**Comment by SreenivasVRao** [comment]
Hi, I'm facing the issue - how did you solve this?

**Comment by hnnazm** [comment]
You need to explicitly define what the type of search. Use `swiper-isearch` instead of `swiper`
In my case, this should solve it.

```
(setq ivy-posframe-display-functions-alist
	     '((swiper-isearch  . nil)
               (t               . ivy-posframe-display-at-frame-center)))
```
