### ISSUE TITLE
ivy-posframe-mode block ivy-mode's ivy-dispatching-done(M-o)

### ISSUE THREAD

**Issue by tshu-w** [tumashu/ivy-posframe#96]
after recently updated, I find I cannot use `M-o` to call `ivy-dispatching-done` in `ivy-minibuffer` If I enabled `ivy-posframe-mode`.

ivy-posframe: 20201005.119
ivy: 20200826.955
GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G2021))
 of 2020-08-25

**Comment by tumashu** [comment]
Should be fixed, please try again.

**Comment by tshu-w** [comment]
it works. thx you for your quick fix.
